# Generated by Django 2.2.5 on 2019-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
