# Generated by Django 2.2.5 on 2019-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190908_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermagalu',
            options={'verbose_name': 'Usuario Magalu', 'verbose_name_plural': 'Usuarios Magalu'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'WishList', 'verbose_name_plural': 'WishLists'},
        ),
        migrations.RemoveField(
            model_name='usermagalu',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usermagalu',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='usermagalu',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usermagalu',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='usermagalu',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermagalu',
            name='name',
            field=models.CharField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='magalu_user',
            field=models.ManyToManyField(to='core.UserMagalu'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
