# Generated by Django 2.1.12 on 2019-09-10 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190909_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=254, null=True)),
                ('product_id', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='magalu_user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='magalu_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserMagalu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WishList'),
        ),
    ]
