# Generated by Django 2.1.12 on 2019-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190910_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermagalu',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
