# Generated by Django 2.1.12 on 2019-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usermagalu_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermagalu',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
