# Generated by Django 2.1.12 on 2019-09-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190910_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('wishlist', 'product_id')},
        ),
    ]
